Add Nomad provider
crazy-max/diun pull request #722
Opened 2022-11-21 21:55 UTC by IamTheFij

I modeled it off the Kubernetes provider a bit. It supports setting task config at group and task levels using services and meta attributes.

2022-11-25 10:22 UTC, crazy-max commented
@IamTheFij Will review this soon, thanks for your contrib!

2022-12-07 23:01 UTC, IamTheFij commented
Just wanted to check in and see if there were any suggested changes here.

2022-12-16 18:07 UTC, crazy-max commented
@IamTheFij It looks mostly fine to me thanks! I will create a Nomad instance on my side to play a bit with it and finalize the review.

2022-12-26 02:50 UTC, crazy-max requested changes
Some minor changes to fix, otherwise nice job!

2022-12-26 02:50 UTC, crazy-max commented on docs/providers/nomad.md
> +Default values are assigned by the Nomad client. If not provided in your Diun configuration, the client will default to using the same config values as the `noamd` cli client.
```suggestion
Default values are assigned by the Nomad client. If not provided in your Diun configuration, the client will default to using the same config values as the `nomad` cli client.
```

2022-12-26 02:50 UTC, crazy-max commented on docs/providers/nomad.md
> +| `diun.enable`       |              | Set to true to enable image analysis of this pod                                                                                                           |
I think right wording is `task`, not `job` right?

```suggestion
| `diun.enable`       |              | Set to true to enable image analysis of this task                                                                                                           |
```

2022-12-26 02:50 UTC, crazy-max commented on docs/providers/nomad.md
> +| `diun.watch_repo`   | `false`      | Watch all tags of this pod image ([be careful](../faq.md#docker-hub-rate-limits) with this setting)                                                        |
```suggestion
| `diun.watch_repo`   | `false`      | Watch all tags of this task image ([be careful](../faq.md#docker-hub-rate-limits) with this setting)                                                        |
```

2022-12-26 10:31 UTC, crazy-max requested changes
Can you squash your commits please? Thanks

2022-12-27 16:36 UTC, crazy-max approved these changes

2022-12-27 16:46 UTC, merged