API Metrics Feature
crazy-max/diun pull request #775
Opened 2023-01-26 14:42 UTC by AthrogatePEQ

Added api end points for pulling metrics and triggering a new scan.

2023-02-15 13:36 UTC, jooola commented
I have the feeling this PR will not be accepted as it is, because you are already proposing other changes unrelated to the prometheus metrics.

Th fastest way to have this feature merged is probably go easy on @crazy-max and provide him with a clean MR easy to review.

2023-02-15 13:47 UTC, jooola requested changes

2023-02-15 13:47 UTC, jooola commented on docs/config/apimetrics.md
> +  scanPath: /v1/scan
Keys have inconsistent casing. I think they should have snake casing.

2023-02-15 13:47 UTC, jooola commented on internal/config/config.go
> +	APIMetrics *model.APIMetrics `yaml:"apimetrics,omitempty" json:"metricsapi,omitempty"`
The yaml and json key are different.

I personally think the naming is not the best, maybe "metrics" alone in better ?

2023-02-15 13:47 UTC, jooola commented on pkg/api/scan/scan.go
> +}
What is this used for in the context of the prometheus metrics ?

2025-10-05 10:50 UTC, stablestud commented
Hi @AthrogatePEQ would be awesome if you could get this merged, as this is really helpful. Would it be a problem if you took a look at @jooola suggestions and try to get it merged?

Thank you!

2026-05-27 22:36 UTC, crazy-max commented
Thanks again for opening this and for the early work on Prometheus metrics.

I'm going to close this PR in favor of #1744, which adds the metrics endpoint with the current configuration model, documentation, authentication support, Prometheus handler error logging, and dedicated e2e coverage.

I did review this implementation while working on the new PR, but #1744 takes a different shape to keep the metrics surface smaller and aligned with the current Diun codebase.

2026-05-27 22:36 UTC, closed without merging